name: property-data
channels:
  - conda-forge
dependencies:
  - libspatialite
  - datasette
  - bambi
  - pandas
  - altair
  - seaborn
  - rich
  - jupyterlab
  - beautifulsoup4
  - openpyxl
  - mkl-service
  - geopandas
  - pip
  - ydata-profiling
  - pip:
      - shapefile-to-sqlite
      - datasette-geojson-map
      - datasette-leaflet-geojson
      - dbfread
      - sqlite_utils
      - googlemaps
  - requests
